                                Assignment on Pandas                                          

Name: Siriseni Meghana Bhavya

Roll no: 238T1A05G9

Batch : 2

Output Prediction

Q1. Array operations and vectorization


In [10]:
import numpy as np
import pandas as pd
arr = np.array([10, 20, 30])
s = pd.Series([10, 20, 30])
print(arr * 2)
print(s * 2)

[20 40 60]
0    20
1    40
2    60
dtype: int64


1.Predict the output of both statements

First Statement:

[20 40 60]

Second Statement:

0      20
1      40
2      60
dtype: int 64

2.Identify one Similarity and one difference between the two data structures

Similarity:

Both perform element-wise multiplication by 2

Difference:

arr is a NumPy array, so it displays only the values.


Explanation: 

Both perform element-wise multiplication by 2, but the NumPy array displays only values while the Pandas Series displays values with their index and data type.

Q2.Boolean Filtering



In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Marks': [45, 80, 65, 90]
})

result = df[df['Marks'] >= 65]

print(result[['Student', 'Marks']])

  Student  Marks
1       B     80
2       C     65
3       D     90


Exact Output:

 Student  Marks

1       B     80

2       C     65

3       D     90

1.Predict the rows displayed

  Student  Marks

1       B     80

2       C     65

3       D     90


2.How many rows and columns will the resulting DataFrame Contain

The resulting DataFrame contains:

3 rows
2 columns

So the shape is:

(3, 2)

Explanation:

 Students B, C, and D have marks ≥ 65, so only these three rows are displayed.

Q3. Descriptive statistics

In [ ]:
#Code
import pandas as pd

df = pd.DataFrame({
    'Marks': [10, 20, 30, 40, 50]
})

print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].median())

30.0
50
30.0


1.Predict all three outputs

30.0

50

30.0


2.Explain how the median differs from the mean

 Answer:

 The mean is the average of all values, while the median is the middle value after arranging the values in order; here, both are 30.




Explanation:

The mean and median are both 30, while the maximum value is 50; the median is the middle value after sorting the data.

Q4.Group-wise Analysis



In [ ]:
#Code
import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary': [40000, 30000, 60000, 50000]
})

print(df.groupby('Department')['Salary'].mean())

Department
HR    40000.0
IT    50000.0
Name: Salary, dtype: float64


1. Predict the output

Department

HR    40000.0

IT    50000.0

Name: Salary, dtype: float64



2. Explain how groupby() calculates the department-wise average.

Answer:

groupby() groups salaries by department and calculates the mean salary for each department.

Q5.Pandas Correlation - Positive


In [ ]:
#Code
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))

1.0


1. Predict the correlation coefficient

Output:

1.0


2. Interpret the direction and strength of the relationship.

Answer:

The coefficient 1.0 indicates a perfect positive relationship, meaning marks increase consistently as study hours increase.

Q6. Pandas Correlation – Negative

In [ ]:
#Code
import pandas as pd

df = pd.DataFrame({
    'Price': [10, 20, 30, 40],
    'Demand': [100, 80, 60, 40]
})

print(df['Price'].corr(df['Demand']))

-1.0


1. Predict the correlation coefficient.

Output:

-1.0

2. Explain what the sign of the coefficient indicates about the relationship.

Answer:

The coefficient -1.0 indicates a perfect negative relationship, meaning demand decreases consistently as price increases.

Code Correction


Q1. JSON and CSV

Question

A CSV file contains a header row, but the following code incorrectly reads the first student's record as column names. Correct the code.



In [ ]:
#Incorrect code
import pandas as pd

df = pd.read_csv("students.csv", header=None)
print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'students.csv'

In [14]:
import pandas as pd
students = pd.DataFrame({
   'ID': [101, 102, 103],
   'Name': ['Asha, R', 'Ravi', 'Neha'],
   'Date': ['2026-09-01', '01/09/2026', '2026-09-03'],
   'Marks': [80, None, None]
})
students.to_csv('students.csv', index=False)

Issue

header=None tells Pandas that the CSV has no header, so the first row is treated as data.

In [15]:
import pandas as pd

df = pd.read_csv("students.csv")

print(df)

    ID     Name        Date  Marks
0  101  Asha, R  2026-09-01   80.0
1  102     Ravi  01/09/2026    NaN
2  103     Neha  2026-09-03    NaN


Output:

Student  Marks

0       A     45

1       B     80

2       C     65

Explanation:

Pandas automatically uses the first row as column names when header=None is removed.

Q2. Data Analysis

Question:

The objective is to display the five highest salaries from a DataFrame. Correct the code.

In [19]:
#Incorrect Code
print(df.sort_values('Salary').head(5))

KeyError: 'Salary'

Issue:

sort_values() sorts in ascending order by default, so head(5) gives the five lowest salaries.

In [16]:
#Corrected Code
import pandas as pd

df = pd.DataFrame({
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})

print(df.sort_values('Salary', ascending=False).head(5))

  Employee  Salary
5        F   70000
3        D   60000
1        B   50000
4        E   45000
0        A   30000


Explanation:

ascending=False sorts salaries from highest to lowest, and head(5) selects the top five.

Q3. Cleaning Data

Question:

A student wants to replace missing marks with the column's mean but writes code that does not update the DataFrame. Correct the code.



In [ ]:
#Incorrect Code
df['Marks'].fillna(df['Marks'].mean())
print(df)

Issue:

fillna() returns a modified Series but does not update df automatically.

In [ ]:
#Corrected Code
import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})

df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

print(df)

   Marks
0   70.0
1   80.0
2   90.0


Explanation:

The missing value is replaced with the mean 80, and the result is assigned back to the Marks column.

Q4. Correlation

Question:

The objective is to calculate the correlation between Hours and Marks. Correct the code.

In [ ]:
#Incorrect Code
print(df.corr(Hours, Marks))

Issue:

Hours and Marks are column names, so they must be accessed as DataFrame columns.



In [ ]:
#Corrected Code
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))

1.0


Explanation:

.corr() calculates the correlation between the two selected columns, and here the relationship is perfectly positive.

Edge Cases

Q1. Two NumPy arrays have shapes (3, 1) and (1, 3). Predict the shape of their element-wise sum and explain how broadcasting works. Why might the result differ from adding two one-dimensional arrays?

In [ ]:
#Code
import numpy as np

a = np.array([[10], [20], [30]])
b = np.array([[1, 2, 3]])

result = a + b

print(result)
print(result.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)


1. Predict the Output of the given code

Output:

[[11 12 13]

 [21 22 23]

 [31 32 33]]
 
(3, 3)

 2. Identify the shapes of arrays a and b before addition.

Answer: 

a has shape (3, 1) and b has shape (1, 3).

 3. Explain how NumPy broadcasting enables the addition.

Answer: 

Broadcasting expands the (3,1) and (1,3) arrays to a compatible (3,3) shape, allowing element-wise addition.

4. What would happen if b was replaced with np.array([1, 2])?

Answer: 

The result would have shape (3, 2) because (3,1) can broadcast with (2,).

[[11 12]

 [21 22]
 
 [31 32]]

Question:

Q2. A CSV file contains commas inside quoted text fields, missing values, and dates in different formats. Explain how incorrect parsing can affect the resulting DataFrame and identify suitable read options or preprocessing steps.

 1: Predict how the quoted comma in "Asha, R" will be handled.

Answer:

 The comma inside "Asha, R" is treated as part of the name because it is enclosed in quotation marks, so it remains one field.

2: Identify the potential issues with the Date and Marks columns.

Answer: 

The Date column contains different date formats, while the Marks column contains missing values (NA).


In [17]:
#3: Rewrite the code to handle missing marks and convert the date column into a suitable date-time format
import pandas as pd
from io import StringIO

data = """ID,Name,Date,Marks
101,"Asha, R",2026-09-01,80
102,Ravi,01/09/2026,
103,Neha,2026-09-03,NA"""

df = pd.read_csv(StringIO(data))

df['Date'] = pd.to_datetime(df['Date'], format='mixed', dayfirst=True)
df['Marks'] = pd.to_numeric(df['Marks'], errors='coerce')

print(df)
print(df.dtypes)

    ID     Name       Date  Marks
0  101  Asha, R 2026-01-09   80.0
1  102     Ravi 2026-09-01    NaN
2  103     Neha 2026-03-09    NaN
ID                int64
Name                str
Date     datetime64[us]
Marks           float64
dtype: object


Output:

    ID      Name       Date         Marks

0  101      Asha, R    2026-09-01   80.0

1  102      Ravi       2026-09-01    NaN

2  103      Neha       2026-09-03    NaN

4: Why should "NA" be investigated before deciding whether it represents a missing value?

Answer:

 "NA" may mean a genuinely missing mark, or it could be a meaningful code such as Not Applicable; therefore, its meaning should be confirmed before treating it as missing data.

Explanation:

pd.to_datetime() converts the different date formats into a consistent date-time format, while pd.to_numeric(..., errors='coerce') converts invalid or missing marks to NaN.

Q3. A salary column contains the values 25000, 30000, 35000, and 10000000. Explain how the extreme value affects the mean compared with the median. Identify which statistic may better represent a typical employee's salary and justify your choice.


In [ ]:
#Given code
import pandas as pd

df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D"],
    "Salary": [25000, 30000, 35000, 10000000]
})

print("Mean:", df["Salary"].mean())
print("Median:", df["Salary"].median())

Mean: 2522500.0
Median: 32500.0


1. Predict the mean and median salary

Output:

Mean: 2547500.0

Median: 32500.0

2.Identify the effect of the extreme salary on the mean

Answer:

The extreme salary of 10,000,000 greatly increases the mean.

3.Which statistic may better represent a typical employee's salary in this dataset? Justify your answer.

Answer:

The median (32,500) better represents a typical employee's salary because the median is less affected by extreme values.


In [ ]:
#4.Write code to identify the employee record with the highest salary and explain why the record should be investigated before removing it
highest = df.loc[df["Salary"].idxmax()]

print(highest)

Employee           D
Salary      10000000
Name: 3, dtype: object


Output:

Employee           D

Salary       10000000

Name: 3, dtype: object

Explanation:

 idxmax() finds the index of the highest salary, and loc[] retrieves the complete employee record. The record should be investigated before removing it because the extreme salary may be a genuine value.

Scenario-Based Questions

Q1.A student assessment dataset contains missing marks, duplicate student records, inconsistent department names such as IT, it, and I.T., and marks stored as text. Develop a cleaning sequence to standardize the data, handle missing values, remove duplicates, and convert marks into a suitable numeric type. State one risk of deleting missing values without investigating why they are missing.

Dataset: student_assessment_dirty.csv

| Student_ID | Student_Name | Department | Assessment |    Marks |
| ---------- | ------------ | ---------- | ---------- | -------: |
| S101       | Asha         | IT         | Python     |       85 |
| S102       | Ravi         | it         | Python     |       78 |
| S103       | Neha         | IT         | Python     |       92 |
| S104       | Karan        | HR         | Python     |    blank |
| S105       | Meera        | HR         | Python     |   Absent |
| S106       | Arjun        | Finance    | Python     |        0 |
| S107       | Priya        | finance    | Python     |       67 |
| S108       | Rahul        | IT         | Python     |       75 |
| S102       | Ravi         | it         | Python     |       78 |
| S109       | Sneha        | I.T.       | Python     |       NA |
| S110       | Varun        | HR         | Python     | 88 marks |
| S111       | Diya         | Finance    | Python     |       91 |
| S112       | Aman         | IT         | Python     |    blank |
| S113       | Nisha        | HR         | Python     |       64 |
| S114       | Kabir        | Finance    | Python     |      105 |


In [18]:
#Code
import pandas as pd
from io import StringIO

data = """Student_ID,Student_Name,Department,Assessment,Marks
S101,Asha,IT,Python,85
S102,Ravi,it,Python,78
S103,Neha,IT,Python,92
S104,Karan,HR,Python,
S105,Meera,HR,Python,Absent
S106,Arjun,Finance,Python,0
S107,Priya,finance,Python,67
S108,Rahul,IT,Python,75
S102,Ravi,it,Python,78
S109,Sneha,I.T.,Python,NA
S110,Varun,HR,Python,88 marks
S111,Diya,Finance,Python,91
S112,Aman,IT,Python,
S113,Nisha,HR,Python,64
S114,Kabir,Finance,Python,105"""

df = pd.read_csv(StringIO(data))

print(df.head())
print(df.info())
print(df.isnull().sum())

df["Department"] = df["Department"].str.strip().str.lower()

df["Department"] = df["Department"].replace({
    "it": "IT",
    "i.t.": "IT",
    "hr": "HR",
    "finance": "Finance"
})

before = len(df)
df = df.drop_duplicates()
records_removed = before - len(df)

df["Mark_Status"] = "Entered"

df.loc[df["Marks"].isna(), "Mark_Status"] = "Not Entered"
df.loc[df["Marks"].astype(str).str.lower().eq("absent"), "Mark_Status"] = "Absent"

df["Marks"] = (
    df["Marks"]
    .astype(str)
    .str.replace(" marks", "", regex=False)
)

df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")

invalid_marks = df.loc[
    (df["Marks"] < 0) | (df["Marks"] > 100),
    ["Student_ID", "Student_Name", "Marks"]
]

df.loc[(df["Marks"] < 0) | (df["Marks"] > 100), "Marks"] = pd.NA
df.loc[df["Marks"].isna() & (df["Mark_Status"] == "Entered"), "Mark_Status"] = "Invalid"

print("\nCleaned DataFrame:")
print(df)

print("\nRecords removed:", records_removed)
print("Missing marks remaining:", df["Marks"].isna().sum())
print("Invalid marks identified:")
print(invalid_marks)

  Student_ID Student_Name Department Assessment   Marks
0       S101         Asha         IT     Python      85
1       S102         Ravi         it     Python      78
2       S103         Neha         IT     Python      92
3       S104        Karan         HR     Python     NaN
4       S105        Meera         HR     Python  Absent
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    15 non-null     str  
 1   Student_Name  15 non-null     str  
 2   Department    15 non-null     str  
 3   Assessment    15 non-null     str  
 4   Marks         12 non-null     str  
dtypes: str(5)
memory usage: 732.0 bytes
None
Student_ID      0
Student_Name    0
Department      0
Assessment      0
Marks           3
dtype: int64

Cleaned DataFrame:
   Student_ID Student_Name Department Assessment  Marks  Mark_Status
0        S101         Asha         IT     Python

Explanation:

The cleaning process standardizes department names, removes duplicate records, converts marks to numeric values, preserves the reason for missing marks, and identifies invalid marks instead of blindly deleting them.